# Generated by Django 3.0 on 2020-12-18 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(verbose_name='Nombre de pièces')),
                ('surface', models.IntegerField(verbose_name='Surface en m²')),
                ('prix', models.IntegerField(verbose_name='Prix de loyer souhaité')),
                ('commune', models.CharField(max_length=254, verbose_name='Commune ou ville')),
                ('adresse', models.CharField(max_length=254, verbose_name='Adresse postale')),
                ('image', models.ImageField(upload_to='C:\\Users\\Tuo\\Desktop\\Projet\\django\\envs\\ndcimmob\\immbo/static/immob/')),
                ('desc', models.TextField(verbose_name='Description du bien')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immob.Offre', verbose_name='Faite un choix')),
                ('type_immob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immob.Types', verbose_name='Type de bien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Besoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(verbose_name='Nombre de pièces')),
                ('surface', models.IntegerField(verbose_name='Surface minimale en m²')),
                ('prix', models.IntegerField(verbose_name='Prix minimum')),
                ('prix_2', models.IntegerField(verbose_name='Prix maximum')),
                ('commune', models.CharField(max_length=254, verbose_name='Commune ou ville')),
                ('adresse', models.CharField(max_length=254, verbose_name='Adresse postale')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immob.Demande', verbose_name='Type de besoin')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immob.Types', verbose_name='Type de bien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom agence')),
                ('status', models.BooleanField()),
                ('localite', models.CharField(max_length=254, verbose_name='Situation géographique')),
                ('numero_agr', models.CharField(max_length=50, verbose_name="Numéro d'aggregation")),
                ('dg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
    ]
