# Generated by Django 3.0 on 2020-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0002_agence_besoins_demande_immobilier_offre_types_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='image_1',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Tuo\\Desktop\\Projet\\django\\envs\\ndcimmob\\immbo/static/immob/'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='image_2',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Tuo\\Desktop\\Projet\\django\\envs\\ndcimmob\\immbo/static/immob/'),
        ),
    ]
