# Generated by Django 3.0 on 2020-12-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0004_auto_20201219_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immob.Ville', verbose_name='Ville ou commune'),
        ),
    ]
