# Generated by Django 3.0 on 2020-12-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0005_auto_20201219_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='news',
            field=models.BooleanField(default=False, verbose_name="Je souhaite m'abonner à la newslater"),
        ),
        migrations.AlterField(
            model_name='user',
            name='ag_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur agence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Prénom'),
        ),
    ]
