# Generated by Django 3.0 on 2020-12-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0006_auto_20201220_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
