# Generated by Django 3.0 on 2020-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immob', '0007_auto_20201221_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='news',
            field=models.BooleanField(verbose_name="Je souhaite m'abonner à la newslater"),
        ),
    ]
